routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //$packets = DB::table('members_packets')->select('packet_id', DB::raw('count(packet_id) as jumlah'))->join('packets', 'packets.id', '=', 'members_packets.packet_id')->groupBy('packet_id')->orderBy('jumlah')->limit(3)->get();
    $packets = App\Packet::has('categories')->orderBy('best_selling', 'desc')->limit(3)->get();
    //dd($packets);
    return view('welcome')->with('packets', $packets);
});


Route::prefix('member')->group(function() {
    
    Route::group(['middleware' => ['auth-member:member'] ], function() {
        Route::get('dashboard', 'MemberController@dashboard')->name('member.dashboard');
        Route::get('paket-saya', 'MemberController@showPacket')->name('member.paket_saya');
        Route::get('paket-saya/{id}/detail', 'MemberController@detailPacket')->name('member.detail_paket')->middleware('packet.activated');
        Route::get('lesson/{id}', 'MemberController@lessonPacket')->name('member.lesson')->middleware('packet.activated');
        Route::put('lessen/{id}/finish', 'MemberController@finishLesson')->name('member.lesson.finish')->middleware('packet.activated');
        Route::get('lesson/{id}/watch/{id_kategori}/', 'MemberController@watch')->name('lesson.watch');
        Route::get('lesson/{id}/watch/{id_kategori}/{slug}', 'MemberController@watch')->name('lesson.video');
        Route::get('lesson/{id}/watch/{id_kategori}/test', 'MemberController@watch')->name('lesson.test');
        Route::post('lesson/{id}/watch/{id_kategori}/test', 'AnswerController@create')->name('lesson.answer');
        Route::post('lesson/addcomment', 'CommentController@member_create')->name('lesson.addcomment');
        Route::put('activation-paket/{id}', 'MemberController@activatePacket')->name('member.packet.activate');
        Route::post('beli-paket', 'MemberController@beliPaket')->name('member.beli');
        Route::post('payment', 'MemberController@payment')->name('member.payment');

        //route exam
        Route::get('lesson/{id}/exam', 'MemberController@exam')->name('member.exam');

        Route::post('lesson/{id}/exam', 'MemberController@examSubmit')->name('member.answer_exam');
    });

    Route::get('register', 'RegisterMemberController@showRegisterForm');
    Route::post('register', 'RegisterMemberController@register')->name('member.register');

    Route::get('login', 'MemberLoginController@showLoginForm')->name('member.login-form');
    Route::post('login', 'MemberLoginController@login')->name('member.login');
    Route::post('logout', 'MemberLoginController@logout')->name('member.logout');

});

Route::get('packets', 'PacketController@indexMember')->name('member.packets');
Route::get('packets/{id}/detail', 'MemberController@detailPacket')->name('member.packets.detail');



Route::prefix('api')->group(function() {
    Route::middleware('auth:tutor')->group(function() {
        Route::get('tutor/notifications', 'ApiController@getNotification');
        Route::get('tutor/refresh-notifications', 'ApiController@refreshNotif');

        Route::get('switch-category/{from}/{to}', 'ApiController@switchCategoryOrder');
        Route::get('switch-video/{from}/{to}', 'ApiController@switchCategoryVideoOrder');

        Route::put('tutor/{id}/syncpacketcategory', 'ApiController@syncPacketCategory')->name('api.sync.paket.category');
        Route::put('category/{id}/synccategoryvideo', 'ApiController@syncCategoryVideo')->name('api.sync.category.video');
    });

    Route::middleware('auth:member')->group(function() {
        Route::get('member/notifications', 'ApiController@getNotification');
        Route::get('member/refresh-notifications', 'ApiController@refreshNotif');
    });
});

Route::prefix('tutor')->group(function() {

    Route::get('login', 'TutorLoginController@showLoginForm')->name('tutor.login-form');
    Route::post('login', 'TutorLoginController@login')->name('tutor.login');
    Route::post('logout', 'TutorLoginController@logout')->name('tutor.logout');

    Route::middleware('auth-tutor:tutor')->group(function() {

        Route::get('dashboard', function() {
            $member = \App\Member::all();
            $packet = \App\Packet::all();
            $category = \App\Category::all();
            $data['member'] = $member->count();
            $data['packet'] = $packet->count();
            $data['category'] = $category->count();
            return view('tutor.dashboard', $data);
        })->name('tutor.dashboard');

        Route::resource('paket', 'PacketController');
        Route::resource('kategori', 'CategoryController');
        Route::resource('tutor', 'TutorController');

        Route::get('kategori/{id_kategori}/view', 'CategoryController@view')->name('kategori.view');
        
        //exam route
        Route::get('exam/{id}', 'ExamController@index')->name('exam.index');
        Route::get('exam/{id}/create', 'ExamController@create')->name('exam.create');
        Route::post('exam/{id}/store', 'ExamController@store')->name('exam.store');
        Route::get('exam/{id}/edit', 'ExamController@edit')->name('exam.edit');
        Route::put('exam/{id}/update', 'ExamController@update')->name('exam.update');

        Route::get('exam/{id}/jawaban_ujian_member', 'ExamController@answerExam')->name('exam.answer');
        Route::put('exam/set_nilai_ujian', 'ExamController@setNilaiExam')->name('exam.answer_test');

        Route::get('member', 'MemberController@indexTutor')->name('tutor.member');
        Route::get('member/{id}/packet', 'MemberController@packetMember')->name('tutor.member.packet');  
        Route::get('member/{id}/packet/{id_paket}/progress', 'MemberController@progressMember')->name('tutor.member.progress');

        //route add paket in category page
        Route::post('kategori/addpaket', 'CategoryController@storePacket')->name('kategori.addpaket');
        Route::get('kategori/{id}/video', 'VideoController@index')->name('video.index');
        Route::get('kategori/{id}/video/create', 'VideoController@create')->name('video.create');
        Route::post('kategori/{id}/video/create', 'VideoController@store')->name('video.store');
        Route::get('kategori/{id_kategori}/video/{id}', 'VideoController@show')->name('video.show');
        Route::get('kategori/{id_kategori}/video/edit/{id}', 'VideoController@edit')->name('video.edit');
        Route::put('kategori/{id_kategori}/video/edit/{id}', 'VideoController@update')->name('video.update');
        Route::DELETE('kategori/{id_kategori}/video/{id}', 'VideoController@destroy')->name('video.destroy');
        Route::get('kategori/{id_kategori}/video/{id}/comment', 'CommentController@showComment')->name('comment.show');
        Route::DELETE('comment/{id}', 'CommentController@deleteComment')->name('comment.delete');
        Route::post('comment/reply', 'CommentController@replyComment')->name('comment.reply');

        Route::get('kategori/{id_kategori}/test', 'TestController@index')->name('kategori.test');
        Route::get('kategori/{id_kategori}/test/create', 'TestController@create')->name('test.create');
        Route::post('kategori/{id_kategori}/test/create', 'TestController@store')->name('test.store');
        Route::get('kategori/test/{id}/edit', 'TestController@edit')->name('test.edit');
        Route::put('kategori/test/{id}/edit', 'TestController@update')->name('test.update');
        Route::get('kategori/test/{id}/answer', 'TestController@answer')->name('test.answer');
        Route::put('kategori/test/answer/', 'AnswerController@setNilai')->name('answer.nilai');

        Route::put('send-sertifikat/{member_id}/{packet_id}', 'AnswerController@sendSertifikat')->name('send_sertifikat');

        Route::post('send-kode', 'MemberController@sendKode')->name('tutor.send-kode');

        Route::get('print-member', 'MemberController@printMember')->name('print.member');

        //nilai test
        Route::get('nilai-test', 'AnswerController@nilaiTest')->name('tutor.nilai.test');
        Route::get('nilai-test/print', 'AnswerController@printNilai')->name('nilai.test.print');

        //nilai ujian
        Route::get('nilai-ujian', 'ExamController@nilaiUjian')->name('tutor.nilai.ujian');
        
        Route::get('nilai-ujian/print', 'ExamController@printUjian')->name('nilai.ujian.print');


        Route::get('payment', 'PacketController@payment')->name('tutor.payment');

        Route::put('payment/{id}', 'PacketController@deletePayment')->name('tutor.payment.delete');

        Route::get('sertifikat', 'SertifikatController@index')->name('tutor.sertifikat');

      

        
        
    });
});
Route::get('generate-sertifikat/member/{id_member}/paket/{id_paket}/sertifikat/{certificate_number}', 'AnswerController@generateSertifikat')->name('tutor.generate-sertifikat');

Route::get('sertifikat/show/{kode}', 'SertifikatController@show')->name('sertifikat.show');

Route::get('verification-failed', function() {
    return view('verification-notice');
})->name('verification.notice');

Route::get('tutor', function(){
    return redirect()->route('tutor.dashboard');
});

Route::get('member', function(){
    return redirect()->back();
});

Route::get('sertifikat', function(){
    return view('tutor.sertifikat.page');
}); 

app/Tutor.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticable;
use Illuminate\Notifications\Notifiable;

class Tutor extends Authenticable
{
    use Notifiable;

    protected $fillable = [
        'email',
        'username',
        'password',
        'name',
        'phone',
        'address',
        'role'
    ];

    protected $hidden = ['password'];

    public function setPasswordAttribute($val)
    {
        return $this->attributes['password'] = bcrypt($val);
    }

    public function packets() {
        return $this->hasMany(Packet::class);
    }

    public function categories() {
        return $this->hasManyThrough(Category::class, Packet::class, 'tutor_id', 'packet_id');
    }

    public function comments() {
        return $this->belongsToMany(Member::class, 'comments', 'tutor_id', 'member_id');
    }

    

    public function chats() {
        return $this->belongsToMany(Member::class, 'chats', 'tutor_id', 'member_id');
    }

    public function members() {
        return $this->belongsToMany(Member::class, 'members_packets', 'packet_id', 'member_id');
    }

    public function isSuperAdmin() {
        if ($this->role == 1) {
            return true;
        }
        return false;
    }

    public function notifications() {
        return $this->morphMany(Notification::class, 'notifable');
    }
}

app/Http/Controllers/TutorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTutorRequest;
use App\Http\Requests\UpdateTutorRequest;
use App\Tutor;

class TutorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tutor.index', ['tutors' => Tutor::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tutor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTutorRequest $request)
    {
        Tutor::create($request->all());

        return redirect()->route('tutor.index')->with('success', 'Tutor berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tutor $tutor)
    {
        return view('tutor.edit', ['tutor' => $tutor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTutorRequest $request, Tutor $tutor)
    {
        $tutor->update($request->all());

        return redirect()->route('tutor.index')->with('success', 'Tutor telah diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tutor $tutor)
    {
        $tutor->delete();

        return redirect()->route('tutor.index')->with('success', 'Tutor telah dihapus');
    }
}

resources/views/tutor/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
<meta name="csrf-token" content="{{ csrf_token() }}">

  <title> @yield('title') | TAW Course</title>

  <!-- Custom fonts for this template -->
  <link href="{{ asset('templates/admin-page/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{{ asset('templates/admin-page/css/sb-admin-2.min.css') }}" rel="stylesheet">

  <!-- Custom styles for this page -->
  <link href="{{ asset('templates/admin-page/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

  <link rel="stylesheet" href="{{ asset('templates/asset/style.css') }}">

</head>
@guest
<body id="page-top" class="bg-gradient-primary">
    <!-- Page Wrapper -->
    @yield('content')
@else
<body id="page-top">
        
    <div id="wrapper">

        @include('tutor.sidebar')
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                @include('tutor.navbar')

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @include('tutor.flash-message')
                    
                    <!-- Page Heading -->
                    <h1 class="h3 mb-3 text-gray-800">@yield('title')</h1>
                    
                    <div id="app">
                        @yield('content')
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            @yield('tutor.footer')
        </div>
        <!-- End of Content Wrapper -->

    </div>
    @endguest
    <!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
<i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yakin akan logout?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            </div>
            <div class="modal-body">Klik logout untuk keluar dari aplikasi</div>
            <div class="modal-footer">
                <form action="{{ route('tutor.logout') }}" method="post">
                    @csrf
                    <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Logout</a>
                </form>
            </div>
        </div>
    </div>
</div>

    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('templates/admin-page/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('templates/admin-page/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('templates/admin-page/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('templates/admin-page/js/sb-admin-2.min.js') }}"></script>

    <!-- Page level plugins -->
    <script src="{{ asset('templates/admin-page/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('templates/admin-page/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ asset('templates/admin-page/js/demo/datatables-demo.js') }}"></script>

    <script>
        (function($){
            function pushAlert(response) {
                var alert = $('#alertsDropdown');
                var html = '';
                

                alert.find('.badge-counter').text(response.count);

                if (response.count == 0) {
                    html += '<a class="dropdown-item d-flex align-items-center" href="#">';
                    html += '<div>Tidak ada pemberitahuan terbaru';
                    html += '</div></a>';
                }else {
                    response.data.forEach(function(item) {
                        html += '<a class="dropdown-item d-flex align-items-center" href="#">';
                        html += '<div>';
                        html += '<div class="small text-gray-500">'+item.date+'</div>';
                        html += '<div class="font-weight-bold">'+item.title+'</div>';
                        html += '<div>'+item.text+'</div>';
                        html += '</div></a>';
                    });
                }

                $('div.dropdown-list').html(html);
            }

            function refreshNotif(response) {
                var alert = $('#alertsDropdown');
                alert.find('.badge-counter').text(response.count);
            }

            $('#alertsDropdown').on('click', function(e) {
                
                $.get('/api/tutor/refresh-notifications', refreshNotif);
                
            });

            $.get('/api/tutor/notifications', pushAlert);
            $.get('/api/member/notifications', pushAlert);
        })(jQuery)
    </script>

    <script src="{{ asset('js/app.js') }}"></script>
    <script>
    $('#dataTable').dataTable( {
        "paging": false
    } );
    </script>
    @stack('scripts')

</body>

</html>

resources/views/tutor/create.blade.php
@extends('tutor.app')

@section('title')
    Tambah Tutor
@endsection

@section('content')
    <!-- Content -->
    <div class="card shadow mb-4 col-md-6">
        <div class="card-body">
            <form action="{{ route('tutor.store') }}" method="post">
                @csrf
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="username" placeholder="Username"  value="{{ old('username') }}">
                        @error('username')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="email" placeholder="Email"  value="{{ old('email') }}">
                        @error('email')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="name" placeholder="Nama"  value="{{ old('name') }}">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="phone" placeholder="No Telp"  value="{{ old('phone') }}">
                        @error('phone')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="password" class="form-control form-control-user" name="password" placeholder="Password"  value="">
                        @error('password')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="password" class="form-control form-control-user" name="password_confirmation" placeholder="Konfirmasi Password"  value="">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <textarea name="address" class="form-control" cols="30" rows="10" placeholder="address"></textarea>
                        @error('address')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <select name="role" class="form-control">
                            <option value="0">Tutor</option>
                            <option value="1">Super Admin</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-12">
                        <input type="submit" value="Tambah Tutor" class="btn btn-primary btn-user btn-block">
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tutor/dashboard.blade.php
@extends('tutor.app')

@section('title')
Selamat Datang Tutor
@endsection

@section('content')
<!-- Content -->

<!-- paket -->
<div class="row">
    <div class="col-md-4">
        <div class="card text-white bg-primary mb-3" style="height: 150px">
            <div class="card-header bg-primary"><i class="fas fa-atlas"></i> Total Paket</div>
            <div class="card-body">
                <h3 class="card-text">{{ $packet }} Paket</h3>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white bg-primary mb-3" style="height: 150px">
            <div class="card-header bg-primary"><i class="far fa-list-alt"></i> Total Kategori</div>
            <div class="card-body">
                <h3 class="card-text">{{ $category }} Kategori</h3>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white bg-primary mb-3" style="height: 150px">
            <div class="card-header bg-primary"><i class="fas fa-users"></i> Total Member</div>
            <div class="card-body">
                <h3 class="card-text">{{ $member }} Orang</h3>
            </div>
        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis possimus veritatis magni! Perferendis voluptas eius alias illo est rerum ipsum cupiditate soluta doloremque deleniti. Debitis temporibus velit blanditiis explicabo quo?</p>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis possimus veritatis magni! Perferendis voluptas eius alias illo est rerum ipsum cupiditate soluta doloremque deleniti. Debitis temporibus velit blanditiis explicabo quo?</p>
        </div>
    </div>
</div>


@endsection

resources/views/tutor/edit.blade.php
@extends('tutor.app')

@section('title')
    Edit Tutor
@endsection

@section('content')
    <!-- Content -->
    <div class="card shadow mb-4 col-md-6">
        <div class="card-body">
            <form action="{{ route('tutor.update', $tutor->id) }}" method="post">
                @csrf
                @method('put')
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="username" placeholder="Username"  value="{{ $tutor->username }}">
                        @error('username')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="email" placeholder="Email"  value="{{ $tutor->email }}">
                        @error('email')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="name" placeholder="Nama"  value="{{ $tutor->name }}">
                        @error('name')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" name="phone" placeholder="No Telp"  value="{{ $tutor->phone }}">
                        @error('phone')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <textarea name="address" class="form-control" cols="30" rows="10" placeholder="address">{{ $tutor->address }}</textarea>
                        @error('address')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12">
                        <select name="role" class="form-control">
                            <option value="0" {{ $tutor->role == 0 ? 'selected' : '' }} >Tutor</option>
                            <option value="1" {{ $tutor->role == 1 ? 'selected' : '' }} >Super Admin</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-12">
                        <input type="submit" value="Update Tutor" class="btn btn-primary btn-user btn-block">
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/tutor/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/tutor/dashboard">
        <!-- <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">TAW Course</div> -->
        <img src="{{ asset('image/logo.png') }}" alt="" width="90%">
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{ urlHasPrefix('dashboard') ? 'active' : '' }}">
        <a class="nav-link" href="/tutor/dashboard">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Master Data
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item {{ urlHasPrefix('paket') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="{{ route('paket.index') }}">
            <i class="fas fa-fw fa-book"></i>
            <span>Paket</span>
        </a>
    </li>
    
    <li class="nav-item {{ urlHasPrefix('kategori') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="{{ route('kategori.index') }}">
            <i class="fas fa-fw fa-address-book"></i>
            <span>Kursus</span>
        </a>
    </li>

    <li class="nav-item {{ urlHasPrefix('member') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="{{ route('tutor.member') }}">
            <i class="fas fa-fw fa-users"></i>
            <span>Member</span>
        </a>
    </li>

    <li class="nav-item {{ urlHasPrefix('payment') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="{{ route('tutor.payment') }}">
            <i class="fas fa-fw fa-receipt"></i>
            <span>Pembayaran</span>
        </a>
    </li>

    <li class="nav-item {{ urlHasPrefix('sertifikat') ? 'active' : '' }}">
        <a class="nav-link collapsed" href="{{ route('tutor.sertifikat') }}">
            <i class="fas fa-fw fa-award"></i>
            <span>Sertifikat</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
            <i class="fas fa-fw fa-file"></i>
            <span>Nilai</span>
        </a>
        <div id="collapsePages" class="collapse {{ urlHasPrefix('nilai') ? 'show' : '' }}" aria-labelledby="headingPages" data-parent="#accordionSidebar" style="">
            <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Laporan Nilai</h6>
            <a class="collapse-item {{ urlHasPrefix('nilai-test') ? 'active' : '' }}" href="{{ route('tutor.nilai.test') }}">Nilai Test</a>
            <a class="collapse-item {{ urlHasPrefix('nilai-ujian') ? 'active' : '' }}" href="{{ route('tutor.nilai.ujian') }}">Nilai Ujian</a>
            
            </div>
        </div>
    </li>




    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->