routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //$packets = DB::table('members_packets')->select('packet_id', DB::raw('count(packet_id) as jumlah'))->join('packets', 'packets.id', '=', 'members_packets.packet_id')->groupBy('packet_id')->orderBy('jumlah')->limit(3)->get();
    $packets = App\Packet::has('categories')->orderBy('best_selling', 'desc')->limit(3)->get();
    //dd($packets);
    return view('welcome')->with('packets', $packets);
});


Route::prefix('member')->group(function() {
    
    Route::group(['middleware' => ['auth-member:member'] ], function() {
        Route::get('dashboard', 'MemberController@dashboard')->name('member.dashboard');
        Route::get('paket-saya', 'MemberController@showPacket')->name('member.paket_saya');
        Route::get('paket-saya/{id}/detail', 'MemberController@detailPacket')->name('member.detail_paket')->middleware('packet.activated');
        Route::get('lesson/{id}', 'MemberController@lessonPacket')->name('member.lesson')->middleware('packet.activated');
        Route::put('lessen/{id}/finish', 'MemberController@finishLesson')->name('member.lesson.finish')->middleware('packet.activated');
        Route::get('lesson/{id}/watch/{id_kategori}/', 'MemberController@watch')->name('lesson.watch');
        Route::get('lesson/{id}/watch/{id_kategori}/{slug}', 'MemberController@watch')->name('lesson.video');
        Route::get('lesson/{id}/watch/{id_kategori}/test', 'MemberController@watch')->name('lesson.test');
        Route::post('lesson/{id}/watch/{id_kategori}/test', 'AnswerController@create')->name('lesson.answer');
        Route::post('lesson/addcomment', 'CommentController@member_create')->name('lesson.addcomment');
        Route::put('activation-paket/{id}', 'MemberController@activatePacket')->name('member.packet.activate');
        Route::post('beli-paket', 'MemberController@beliPaket')->name('member.beli');
        Route::post('payment', 'MemberController@payment')->name('member.payment');

        //route exam
        Route::get('lesson/{id}/exam', 'MemberController@exam')->name('member.exam');

        Route::post('lesson/{id}/exam', 'MemberController@examSubmit')->name('member.answer_exam');
    });

    Route::get('register', 'RegisterMemberController@showRegisterForm');
    Route::post('register', 'RegisterMemberController@register')->name('member.register');

    Route::get('login', 'MemberLoginController@showLoginForm')->name('member.login-form');
    Route::post('login', 'MemberLoginController@login')->name('member.login');
    Route::post('logout', 'MemberLoginController@logout')->name('member.logout');

});

Route::get('packets', 'PacketController@indexMember')->name('member.packets');
Route::get('packets/{id}/detail', 'MemberController@detailPacket')->name('member.packets.detail');



Route::prefix('api')->group(function() {
    Route::middleware('auth:tutor')->group(function() {
        Route::get('tutor/notifications', 'ApiController@getNotification');
        Route::get('tutor/refresh-notifications', 'ApiController@refreshNotif');

        Route::get('switch-category/{from}/{to}', 'ApiController@switchCategoryOrder');
        Route::get('switch-video/{from}/{to}', 'ApiController@switchCategoryVideoOrder');

        Route::put('tutor/{id}/syncpacketcategory', 'ApiController@syncPacketCategory')->name('api.sync.paket.category');
        Route::put('category/{id}/synccategoryvideo', 'ApiController@syncCategoryVideo')->name('api.sync.category.video');
    });

    Route::middleware('auth:member')->group(function() {
        Route::get('member/notifications', 'ApiController@getNotification');
        Route::get('member/refresh-notifications', 'ApiController@refreshNotif');
    });
});

Route::prefix('tutor')->group(function() {

    Route::get('login', 'TutorLoginController@showLoginForm')->name('tutor.login-form');
    Route::post('login', 'TutorLoginController@login')->name('tutor.login');
    Route::post('logout', 'TutorLoginController@logout')->name('tutor.logout');

    Route::middleware('auth-tutor:tutor')->group(function() {

        Route::get('dashboard', function() {
            $member = \App\Member::all();
            $packet = \App\Packet::all();
            $category = \App\Category::all();
            $data['member'] = $member->count();
            $data['packet'] = $packet->count();
            $data['category'] = $category->count();
            return view('tutor.dashboard', $data);
        })->name('tutor.dashboard');

        Route::resource('paket', 'PacketController');
        Route::resource('kategori', 'CategoryController');
        Route::resource('tutor', 'TutorController');

        Route::get('kategori/{id_kategori}/view', 'CategoryController@view')->name('kategori.view');
        
        //exam route
        Route::get('exam/{id}', 'ExamController@index')->name('exam.index');
        Route::get('exam/{id}/create', 'ExamController@create')->name('exam.create');
        Route::post('exam/{id}/store', 'ExamController@store')->name('exam.store');
        Route::get('exam/{id}/edit', 'ExamController@edit')->name('exam.edit');
        Route::put('exam/{id}/update', 'ExamController@update')->name('exam.update');

        Route::get('exam/{id}/jawaban_ujian_member', 'ExamController@answerExam')->name('exam.answer');
        Route::put('exam/set_nilai_ujian', 'ExamController@setNilaiExam')->name('exam.answer_test');

        Route::get('member', 'MemberController@indexTutor')->name('tutor.member');
        Route::get('member/{id}/packet', 'MemberController@packetMember')->name('tutor.member.packet');  
        Route::get('member/{id}/packet/{id_paket}/progress', 'MemberController@progressMember')->name('tutor.member.progress');

        //route add paket in category page
        Route::post('kategori/addpaket', 'CategoryController@storePacket')->name('kategori.addpaket');
        Route::get('kategori/{id}/video', 'VideoController@index')->name('video.index');
        Route::get('kategori/{id}/video/create', 'VideoController@create')->name('video.create');
        Route::post('kategori/{id}/video/create', 'VideoController@store')->name('video.store');
        Route::get('kategori/{id_kategori}/video/{id}', 'VideoController@show')->name('video.show');
        Route::get('kategori/{id_kategori}/video/edit/{id}', 'VideoController@edit')->name('video.edit');
        Route::put('kategori/{id_kategori}/video/edit/{id}', 'VideoController@update')->name('video.update');
        Route::DELETE('kategori/{id_kategori}/video/{id}', 'VideoController@destroy')->name('video.destroy');
        Route::get('kategori/{id_kategori}/video/{id}/comment', 'CommentController@showComment')->name('comment.show');
        Route::DELETE('comment/{id}', 'CommentController@deleteComment')->name('comment.delete');
        Route::post('comment/reply', 'CommentController@replyComment')->name('comment.reply');

        Route::get('kategori/{id_kategori}/test', 'TestController@index')->name('kategori.test');
        Route::get('kategori/{id_kategori}/test/create', 'TestController@create')->name('test.create');
        Route::post('kategori/{id_kategori}/test/create', 'TestController@store')->name('test.store');
        Route::get('kategori/test/{id}/edit', 'TestController@edit')->name('test.edit');
        Route::put('kategori/test/{id}/edit', 'TestController@update')->name('test.update');
        Route::get('kategori/test/{id}/answer', 'TestController@answer')->name('test.answer');
        Route::put('kategori/test/answer/', 'AnswerController@setNilai')->name('answer.nilai');

        Route::put('send-sertifikat/{member_id}/{packet_id}', 'AnswerController@sendSertifikat')->name('send_sertifikat');

        Route::post('send-kode', 'MemberController@sendKode')->name('tutor.send-kode');

        Route::get('print-member', 'MemberController@printMember')->name('print.member');

        //nilai test
        Route::get('nilai-test', 'AnswerController@nilaiTest')->name('tutor.nilai.test');
        Route::get('nilai-test/print', 'AnswerController@printNilai')->name('nilai.test.print');

        //nilai ujian
        Route::get('nilai-ujian', 'ExamController@nilaiUjian')->name('tutor.nilai.ujian');
        
        Route::get('nilai-ujian/print', 'ExamController@printUjian')->name('nilai.ujian.print');


        Route::get('payment', 'PacketController@payment')->name('tutor.payment');

        Route::put('payment/{id}', 'PacketController@deletePayment')->name('tutor.payment.delete');

        Route::get('sertifikat', 'SertifikatController@index')->name('tutor.sertifikat');

      

        
        
    });
});
Route::get('generate-sertifikat/member/{id_member}/paket/{id_paket}/sertifikat/{certificate_number}', 'AnswerController@generateSertifikat')->name('tutor.generate-sertifikat');

Route::get('sertifikat/show/{kode}', 'SertifikatController@show')->name('sertifikat.show');

Route::get('verification-failed', function() {
    return view('verification-notice');
})->name('verification.notice');

Route::get('tutor', function(){
    return redirect()->route('tutor.dashboard');
});

Route::get('member', function(){
    return redirect()->back();
});

Route::get('sertifikat', function(){
    return view('tutor.sertifikat.page');
}); 

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'category_name',
        'number_ofvideos',
        'description',
        'packet_id',
        'file_pdf'
    ];

    public function packet() {
        return $this->belongsTo(Packet::class, 'packet_id');
    }

    public function progresses() {
        return $this->belongsToMany(Member::class, 'progresses', 'category_id', 'member_id');
    }

    public function videos() {
        return $this->hasMany(Video::class, 'category_id');
    }

    public function isLatestCategory() {
        $latestCategory = $this->packet->categories()->orderBy('created_at', 'desc')->first();
        
        if ($this->id == $latestCategory->id) {
            return true;
        }

        return false;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Packet;
use App\Video;
use App\Test;
use App\Http\Requests\StoreCategory;
use App\Tutor;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $packet;

    public function __construct()
    {
        $this->packet = new Packet();
    }

    public function index()
    {
        $user = Auth::user();
        $data['categories'] = $user->categories;
        return view('tutor.category.index', $data);
    }

    public function view($category_id){
        $user = Auth::user();
        $data['categories'] = $user->categories->find($category_id);
        $data['videos'] = Video::where('category_id', $category_id)->get();
        $data['tests'] = Test::where('category_id', $category_id)->first();
        return view('tutor.category.view', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $data['packets'] = $user->packets;
        $data['tutors'] = Tutor::all();
        return view('tutor.category.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategory $request)
    {
        $store_file = $request->file('file_pdf')->store('file_pdf');
        
        $insert = Category::create([
            'category_name' => $request->category_name,
            'description' => $request->description,
            'file_pdf' => $request->file_pdf->hashName(),
            'packet_id' => $request->packet_id
        ]);

        return redirect()->route('test.create', ['id_kategori' => $insert->id])->with('success', 'Berhasil menambah data kategori, silahkan tambah test');
    }

    public function storePacket(Request $request){
        $this->validate($request, [
            'packet_name' => 'required',
            'packet_price' => 'required',
            'description' => 'required',
            'tutor_id' => 'required|numeric'  
        ]);
        
        $this->packet->packet_name = $request->packet_name;
        $this->packet->packet_price = $request->packet_price;
        $this->packet->description = $request->description;
        $this->packet->tutor_id = $request->tutor_id;
        $this->packet->number_of_categories = 0;
        $this->packet->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Category::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $data['category'] = Category::find($id);
        $data['packets'] = $user->packets;
        $data['videos'] = Category::find($id)->videos()->get();
        return view('tutor.category.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCategory $request, $id)
    {   
        $category = Category::find($id);
        $file_name = $category->file_pdf;
        if($request->hasFile('file_pdf') == true){
            unlink('storage/file_pdf/'.$file_name);
            $request->file('file_pdf')->store('file_pdf');
            $file_name = $request->file_pdf->hashName();
        }

        Category::find($id)->update([
            'category_name' => $request->category_name,
            'description' => $request->description,
            'packet_id' => $request->packet_id,
            'file_pdf' => $file_name
        ]);
        
        $this->packet->updateCategoryPacket($request->packet_id);

        return redirect()->route('kategori.index')->with('success', 'Berhasil mengedit data kategori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $packet = Packet::find($category->packet_id);

        $packet->update(['number_of_categories' => $packet->number_of_categories - 1]);

        unlink('storage/file_pdf/'.$category->file_pdf);
        $category->delete();
        return redirect()->route('kategori.index')->with('success', 'Berhasil menghapus data kategori');
        
    }
}

app/Http/Controllers/TutorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTutorRequest;
use App\Http\Requests\UpdateTutorRequest;
use App\Tutor;

class TutorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tutor.index', ['tutors' => Tutor::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tutor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTutorRequest $request)
    {
        Tutor::create($request->all());

        return redirect()->route('tutor.index')->with('success', 'Tutor berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tutor $tutor)
    {
        return view('tutor.edit', ['tutor' => $tutor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTutorRequest $request, Tutor $tutor)
    {
        $tutor->update($request->all());

        return redirect()->route('tutor.index')->with('success', 'Tutor telah diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tutor $tutor)
    {
        $tutor->delete();

        return redirect()->route('tutor.index')->with('success', 'Tutor telah dihapus');
    }
}

resources/views/tutor/category/create.blade.php
@extends('tutor.app')

@section('title')
Tambah Kategori
@endsection

@section('content')
<!-- Content -->
<div class="card shadow mb-4 col-md-6">
    <div class="card-body">
        <form action="{{ route('kategori.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-group row">
                <div class="col-sm-12">
                    <input type="text" class="form-control form-control-user" name="category_name" placeholder="Nama Kategori"  value="{{ old('category_name') }}">
                    @error('category_name')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12">
                    <select name="packet_id" class="form-control">
                        <option value="">- Pilih Paket -</option>
                        @foreach($packets as $packet)
                            <option value="{{ $packet->id }}">{{ $packet->packet_name }}</option>
                        @endforeach
                    </select>
                    <p>Paket anda tidak ada? <a href="" data-toggle="modal" data-target="#addPaketModal">Klik disini</a>  untuk menambahkan paket baru </p>
                    @error('packet_id')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="file_pdf">Materi PDF</label>
                    <input type="file" name="file_pdf" class="form-control">
                    @error('file_pdf')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="description">Deskripsi</label>
                    <textarea name="description" id="mytextarea" class="form-control" placeholder="Masukan description Paket">{{ old('description') }}</textarea>
                    @error('description')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
           
            <div class="form-group row">
                <div class="col-md-12">
                    <input type="submit" value="Tambah Kategori" class="btn btn-primary btn-user btn-block">
                </div>
            </div>
        </form>
    </div>
</div>

<!-- DETAIL Modal-->
<div class="modal fade" id="addPaketModal" tabindex="-1" role="dialog" aria-labelledby="addPaketModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="detailModalLabel">Tambah Paket</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('kategori.addpaket') }}" method="post">
                    @csrf
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <input type="text" class="form-control form-control-user" name="packet_name" placeholder="Nama Paket"  value="{{ old('packet_name') }}">
                            @error('packet_name')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <input type="number" class="form-control form-control-user" name="packet_price" placeholder="price Paket" value="{{ old('packet_price') }}">
                            @error('packet_price')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <textarea name="description" id="mytextarea" class="form-control" placeholder="Masukan description Paket">{{ old('description') }}</textarea>
                            @error('description')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="hidden" name="tutor_id" value="{{ Auth::user()->id }}">
                            @error('tutor_id')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="submit" value="Tambah Paket" class="btn btn-primary btn-user btn-block">
                        </div>
                    </div>
                </form>
            </div>
           
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>


<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'mytextarea' );
</script>

@endpush

resources/views/tutor/category/edit.blade.php
@extends('tutor.app')

@section('title')
Edit Kategori
@endsection

@section('content')
<!-- Content -->
<div class="card shadow mb-4 col-md-6">
    <div class="card-body">
        <form action="{{ route('kategori.update', ['id' => $category->id]) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group row">
                <div class="col-sm-12">
                    <input type="text" class="form-control form-control-user" name="category_name" placeholder="Nama Kategori"  value="{{ $category->category_name }}">
                    @error('category_name')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12">
                    <select name="packet_id" class="form-control">
                        <option value="">- Pilih Paket -</option>
                        @foreach($packets as $packet)
                            <option value="{{ $packet->id }}" {{ $category->packet_id == $packet->id ? 'selected' : '' }} >{{ $packet->packet_name }}</option>
                        @endforeach
                    </select>
                    @error('packet_id')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="file_pdf">Materi</label>
                    <input type="file" name="file_pdf" class="form-control">
                    @error('file_pdf')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="description">Deskripsi</label>
                    <textarea name="description" id="mytextarea" class="form-control" placeholder="Masukan description Paket">{{ $category->description }}</textarea>
                    @error('description')
                        <span class="text-danger">{{ $message }}</span>
                    @enderror
                </div>
            </div>
            <!-- <div class="form-group row">
                <div class="col-md-12">
                    <label for="">Urutan Video</label>
                    <list-drag list="{{ $videos }}" name="title" sync-url="/api/switch-video"></list-drag>
                </div>
            </div> -->
           
            <div class="form-group row">
                <div class="col-md-12">
                    <input type="submit" value="Edit Kategori" class="btn btn-primary btn-user btn-block">
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('scripts')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'mytextarea' );
</script>

@endpush

resources/views/tutor/category/index.blade.php
@extends('tutor.app')

@section('title')
Data Kategori Paket
@endsection

@section('content')
<!-- Content -->

<a href="{{ route('kategori.create') }}" class="btn btn-outline-primary mb-3">Tambah Kategori</a>

<div class="card shadow mb-4">
                       
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-category" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama Kategori</th>
                        <th>Paket</th>
                        <th>Materi</th>
                        <th>Jumlah Video</th>
                        <th>Action</th>
                    </tr>
                </thead>
            
                <tbody>
                    @foreach($categories as $row)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $row->category_name }}</td>
                        <td>{{ $row->packet->packet_name }}</td>
                        <td><a href="{{ asset('storage/file_pdf/'.$row->file_pdf) }}">Download</a></td>
                        <td>{{ $row->videos->count() }}</td>
                        <td>
                            <!-- <a href="{{ route('video.index', ['id_kategori' => $row->id ]) }}" class="btn btn-outline-success btn-sm">Lihat Video</a>
                            <a href="{{ route('kategori.test', ['id_kategori' => $row->id ]) }}" class="btn btn-outline-primary btn-sm">Lihat Test</a> -->
                            <a href="{{ route('kategori.view', ['id_kategori' => $row->id ]) }}" class="btn btn-info btn-sm"><i class="fa fa-eye"></i></a>
                            <a href="{{ route('kategori.edit', ['id' => $row->id]) }}" class="btn btn-warning btn-sm"><i class="fa fa-cog"></i></a>
                            <button value="{{ $row->id }}" class="btn btn-danger btn-sm delete-btn" data-toggle="modal" data-id="{{ $row->id }}" data-target="#deleteModal"><i class="fa fa-trash"></i></button>
                        </td>
                       
                    </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- DETAIL Modal-->
<div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="detailModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="detailModalLabel">Detail Paket</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table detail-table">
                    <tr>
                        <td>Deskripsi</td>
                    </tr>  
                    <tr>
                        <td class="description"></td>
                    </tr>
                    <tr>
                        <td class="number_ofvideos"></td>
                    </tr>
                    <tr>
                        <td class="packet_name"></td>
                    </tr>

                </table>
            </div>
            <div class="modal-footer">
                <a class="btn btn-light" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>

<!-- Delete Modal-->
<div class="modal fade deleteModal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Yakin hapus paket?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            </div>
            <div class="modal-body">Paket yang sudah dihapus tidak dapat dikembalikan</div>
            <!-- <input type="text" class="unique"> -->
        
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger btn-del">Hapus</button>
            </div>
           
        </div>
    </div>
</div>

@endsection

@push('scripts')

<script>

$(document).ready(function(){
    $('.delete-btn').click(function(){
        var id = $(this);
       console.log(id.data('id'));
      // $('.unique').val(id.data('id'));
        $('.btn-del').click(function(){
            $.ajax({
                url : "kategori/"+id.data('id'),
                method : "POST",
                data : {
                    _token : "{{csrf_token()}}",
                    _method : "DELETE",
                }
            })
            .then(function(data){
               // console.log(data);
                location.reload();
            });
        });
    });

});

</script>

@endpush